/*!
 * Triangle FIDO2 Plugin
 * https://github.com/localzet-dev/FIDO2
 *
 * Copyright Ivan Zorin <creator@localzet.com>
 * Released under the AGPL-3.0 license
 * https://www.gnu.org/licenses/agpl
 *
 * Date: 2023-03-21T22:48Z
 */
async function createRegistration(){try{if(!navigator.credentials||!navigator.credentials.create)throw new Error("Браузер не поддерживается");axios.get("/app/FIDO/create").then((async function(r){const e=r.data;if(!1===e.success)throw new Error(e.msg||"Произошла неизвестная ошибка");recursiveBase64StrToArrayBuffer(e);const t=await navigator.credentials.create(e),a={transports:t.response.getTransports?t.response.getTransports():null,clientDataJSON:t.response.clientDataJSON?arrayBufferToBase64(t.response.clientDataJSON):null,attestationObject:t.response.attestationObject?arrayBufferToBase64(t.response.attestationObject):null};axios.post("/app/FIDO/create",a).then((function(r){const e=r.data;if(e.success)return!0;throw new Error(e.msg)})).catch((function(r){throw new Error(r||"Произошла неизвестная ошибка")}))})).catch((function(r){throw new Error(r||"Произошла неизвестная ошибка")}))}catch(r){return console.error(r),!1}}async function checkRegistration(){try{if(!navigator.credentials||!navigator.credentials.create)throw new Error("Браузер не поддерживается");axios.get("/app/FIDO/verify").then((async function(r){const e=r.data;if(!1===e.success)throw new Error(e.msg);recursiveBase64StrToArrayBuffer(e);const t=await navigator.credentials.get(e),a={id:t.rawId?arrayBufferToBase64(t.rawId):null,clientDataJSON:t.response.clientDataJSON?arrayBufferToBase64(t.response.clientDataJSON):null,authenticatorData:t.response.authenticatorData?arrayBufferToBase64(t.response.authenticatorData):null,signature:t.response.signature?arrayBufferToBase64(t.response.signature):null,userHandle:t.response.userHandle?arrayBufferToBase64(t.response.userHandle):null};axios.post("/app/FIDO/verify",a).then((function(r){const e=r.data;if(e.success)return!0;throw new Error(e.msg)})).catch((function(r){throw new Error(r||"Произошла неизвестная ошибка")}))})).catch((function(r){throw new Error(r||"Произошла неизвестная ошибка")}))}catch(r){return console.error(r),!1}}function recursiveBase64StrToArrayBuffer(r){let e="=?BINARY?B?",t="?=";if("object"==typeof r)for(let a in r)if("string"==typeof r[a]){let n=r[a];if(n.substring(0,11)===e&&n.substring(n.length-2)===t){n=n.substring(11,n.length-2);let e=window.atob(n),t=e.length,s=new Uint8Array(t);for(let r=0;r<t;r++)s[r]=e.charCodeAt(r);r[a]=s.buffer}}else recursiveBase64StrToArrayBuffer(r[a])}function arrayBufferToBase64(r){let e="",t=new Uint8Array(r),a=t.byteLength;for(let r=0;r<a;r++)e+=String.fromCharCode(t[r]);return window.btoa(e)}
//# sourceMappingURL=fido.js.map
